# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 计算传播学
author: Cheng-Jun Wang
logo: ./img/logo/socrates_jump.gif

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

exclude_patterns: [pattern1/*, README.md, deploy.sh, LICENSE]

parse:
  myst_enable_extensions:
    # https://myst-parser.readthedocs.io/en/latest/syntax/optional.html
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - html_image
    - amsmath
    - dollarmath
    - linkify
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context


only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex
  latex_engine: xelatex


# Information about where the book exists on the web
repository:
  url: https://MiaoJiajia0307.github.io  # Online location of your book
  path_to_book: /  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  colab_url: "https://colab.research.google.com"
  

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  comments:
    hypothesis: true
    # utterances:
    #   repo: "chengjun/mybook"

# https://jupyterbook.org/interactive/interactive.html
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
